org.gradle.jvmargs=-Xmx2G
org.gradle.parallel=true

# MC 26.1+ не обфусцирован — mappings не нужны
fabric.loom.disableObfuscation=true

minecraft_version=26.1.2
loader_version=0.19.1
fabric_version=0.149.1+26.1.2

mod_version=0.1.1
modmenu_version=18.0.0-alpha.8
maven_group=com.tailscale
archives_base_name=tailmod
